name: Deploy snapshot package to GitHub Packages

on:
  workflow_run:
    workflows: [ "Compile snapshot with Maven" ]
    branches:
      - master
      - development
      - api-fixes
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'api-fixes'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Deploy Package
        run: mvn --batch-mode -DskipTests -DuseGitHubPackages deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}