name: Deploy snapshot package to GitHub Packages

on:
  push:
    branches:
      - master
      - development
      - api-fixes

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'api-fixes'
      - name: Set up JDK 17.0.5
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.5'
          distribution: 'adopt'
      - name: Package with Maven
        run: |
          mvn clean package
          ls

  publish:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'api-fixes'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy Package
        run: mvn --batch-mode -DskipTests -DuseGitHubPackages deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}