name: Deploy snapshot package to GitHub Packages

on:
  push:
    branches:
      - master
      - development
      - api-fixes

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17.0.5
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.5'
          distribution: 'adopt'
      - name: Publish Package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}